/**
 * Google Gemini AI Service
 * 
 * Handles AI-powered recovery plan generation using Google Gemini API
 */

import { FirestoreStudent } from '@/types/firebase';

// Get API key from environment (works in both Vite and Node.js)
const getGeminiApiKey = (): string => {
  // Vite environment (browser)
  if (typeof import.meta !== 'undefined' && import.meta.env) {
    return import.meta.env.VITE_GEMINI_API_KEY || '';
  }
  // Node.js environment (scripts)
  if (typeof process !== 'undefined' && process.env) {
    return process.env.VITE_GEMINI_API_KEY || '';
  }
  return '';
};

const GEMINI_API_KEY = getGeminiApiKey();
// Use v1 API with gemini-pro model (most widely available)
const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent';

export interface GeminiRecoveryPlanResponse {
  weakTopics: string[];
  dailyStudyHours: number;
  schedule: {
    day: string;
    focus: string;
    duration: string;
  }[];
  resources: {
    title: string;
    type: 'Video Course' | 'Exercises' | 'Community' | 'Mentorship' | 'Article' | 'Book';
    url: string;
    description?: string;
  }[];
  strategies: string[];
}

/**
 * Generate recovery plan using Gemini AI
 */
export async function generateRecoveryPlanWithGemini(
  student: FirestoreStudent
): Promise<GeminiRecoveryPlanResponse> {
  const apiKey = getGeminiApiKey();
  if (!apiKey) {
    throw new Error('Gemini API key not configured. Please set VITE_GEMINI_API_KEY in your .env file.');
  }

  // Build prompt for Gemini
  const prompt = buildRecoveryPlanPrompt(student);

  try {
    // Try v1 API with gemini-pro first
    let apiUrl = 'https://generativelanguage.googleapis.com/v1/models/gemini-pro:generateContent';
    let response = await fetch(
      `${apiUrl}?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
              ],
            },
          ],
          generationConfig: {
            temperature: 0.7,
            topK: 40,
            topP: 0.95,
            maxOutputTokens: 2048,
          },
        }),
      }
    );

    // If v1 fails with 404, try v1beta with gemini-1.5-flash
    if (!response.ok && response.status === 404) {
      console.log('Trying v1beta API with gemini-1.5-flash...');
      apiUrl = 'https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent';
      response = await fetch(
        `${apiUrl}?key=${apiKey}`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: prompt,
                  },
                ],
              },
            ],
            generationConfig: {
              temperature: 0.7,
              topK: 40,
              topP: 0.95,
              maxOutputTokens: 2048,
            },
          }),
        }
      );
    }

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `Gemini API error: ${response.status} ${response.statusText}. ${JSON.stringify(errorData)}`
      );
    }

    const data = await response.json();

    // Extract the generated text
    const generatedText = data.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!generatedText) {
      throw new Error('No content generated by Gemini API');
    }

    // Parse the JSON response from Gemini
    const recoveryPlan = parseGeminiResponse(generatedText, student);

    return recoveryPlan;
  } catch (error: any) {
    console.error('Gemini API error:', error);
    throw new Error(`Failed to generate recovery plan with Gemini: ${error.message}`);
  }
}

/**
 * Build the prompt for Gemini AI
 */
function buildRecoveryPlanPrompt(student: FirestoreStudent): string {
  const avgQuizScore = student.quizScores.length > 0
    ? Math.round(student.quizScores.reduce((a, b) => a + b, 0) / student.quizScores.length)
    : 0;
  
  const assignmentCompletion = student.totalAssignments > 0
    ? Math.round((student.assignmentsSubmitted / student.totalAssignments) * 100)
    : 0;

  return `You are an AI educational advisor helping to create a personalized recovery plan for a student at risk of academic failure.

STUDENT PROFILE:
- Name: ${student.name}
- Course: ${student.course}
- Risk Level: ${student.riskLevel}
- Risk Score: ${student.riskScore}/100
- Attendance: ${student.attendancePercentage}%
- Average Quiz Score: ${avgQuizScore}%
- Assignment Completion: ${assignmentCompletion}%
- Engagement Score: ${student.engagementScore}/100
- Risk Factors: ${student.riskFactors.join(', ')}

RECENT QUIZ SCORES: ${student.quizScores.slice(-5).join(', ')}%

TASK:
Generate a comprehensive, actionable recovery plan in JSON format. The plan should be personalized based on the student's specific weaknesses and risk factors.

REQUIREMENTS:
1. Identify 3-5 weak topics based on their performance data
2. Recommend daily study hours (2-4 hours based on risk level)
3. Create a weekly study schedule (Monday through Weekend) with specific focus areas
4. Suggest 4-5 learning resources (mix of video courses, exercises, community, mentorship)
5. Provide 5-7 actionable study strategies

OUTPUT FORMAT (JSON only, no markdown):
{
  "weakTopics": ["topic1", "topic2", "topic3"],
  "dailyStudyHours": 3,
  "schedule": [
    {"day": "Monday", "focus": "specific focus area", "duration": "X hours"},
    {"day": "Tuesday", "focus": "specific focus area", "duration": "X hours"},
    {"day": "Wednesday", "focus": "specific focus area", "duration": "X hours"},
    {"day": "Thursday", "focus": "specific focus area", "duration": "X hours"},
    {"day": "Friday", "focus": "specific focus area", "duration": "X hours"},
    {"day": "Weekend", "focus": "specific focus area", "duration": "X hours"}
  ],
  "resources": [
    {"title": "Resource name", "type": "Video Course", "url": "#", "description": "Brief description"},
    {"title": "Resource name", "type": "Exercises", "url": "#", "description": "Brief description"},
    {"title": "Resource name", "type": "Community", "url": "#", "description": "Brief description"},
    {"title": "Resource name", "type": "Mentorship", "url": "#", "description": "Brief description"}
  ],
  "strategies": [
    "Specific actionable strategy 1",
    "Specific actionable strategy 2",
    "Specific actionable strategy 3",
    "Specific actionable strategy 4",
    "Specific actionable strategy 5"
  ]
}

IMPORTANT:
- Make the plan specific and actionable, not generic
- Base recommendations on the actual performance data provided
- Use appropriate study hours for the risk level (High: 4h, Medium: 3h, Low: 2h)
- Focus on the identified risk factors
- Return ONLY valid JSON, no additional text or markdown formatting`;
}

/**
 * Parse Gemini's response and extract the recovery plan
 */
function parseGeminiResponse(
  responseText: string,
  student: FirestoreStudent
): GeminiRecoveryPlanResponse {
  try {
    // Try to extract JSON from the response (Gemini might wrap it in markdown)
    let jsonText = responseText.trim();

    // Remove markdown code blocks if present
    jsonText = jsonText.replace(/```json\n?/g, '').replace(/```\n?/g, '').trim();

    // Try to find JSON object in the text
    const jsonMatch = jsonText.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      jsonText = jsonMatch[0];
    }

    const parsed = JSON.parse(jsonText);

    // Validate and normalize the response
    return {
      weakTopics: Array.isArray(parsed.weakTopics) ? parsed.weakTopics : [],
      dailyStudyHours: typeof parsed.dailyStudyHours === 'number' 
        ? parsed.dailyStudyHours 
        : student.riskLevel === 'High' ? 4 : student.riskLevel === 'Medium' ? 3 : 2,
      schedule: Array.isArray(parsed.schedule) 
        ? parsed.schedule.map((item: any) => ({
            day: item.day || '',
            focus: item.focus || '',
            duration: item.duration || '2 hours',
            completed: false,
          }))
        : getDefaultSchedule(student.riskLevel),
      resources: Array.isArray(parsed.resources)
        ? parsed.resources.map((item: any) => ({
            title: item.title || '',
            type: (item.type || 'Video Course') as any,
            url: item.url || '#',
            description: item.description || '',
          }))
        : getDefaultResources(),
      strategies: Array.isArray(parsed.strategies) ? parsed.strategies : [],
    };
  } catch (error) {
    console.error('Failed to parse Gemini response:', error);
    console.error('Response text:', responseText);
    // Fallback to default plan if parsing fails
    return getFallbackRecoveryPlan(student);
  }
}

/**
 * Get default schedule if Gemini response is invalid
 */
function getDefaultSchedule(riskLevel: 'Low' | 'Medium' | 'High') {
  const hours = riskLevel === 'High' ? 4 : riskLevel === 'Medium' ? 3 : 2;
  return [
    { day: 'Monday', focus: 'Review fundamentals', duration: `${Math.ceil(hours * 0.5)} hours`, completed: false },
    { day: 'Tuesday', focus: 'Practice problems', duration: `${Math.ceil(hours * 0.5)} hours`, completed: false },
    { day: 'Wednesday', focus: 'Concept clarification', duration: `${Math.ceil(hours * 0.4)} hours`, completed: false },
    { day: 'Thursday', focus: 'Group study session', duration: `${Math.ceil(hours * 0.5)} hours`, completed: false },
    { day: 'Friday', focus: 'Mock tests', duration: `${Math.ceil(hours * 0.4)} hours`, completed: false },
    { day: 'Weekend', focus: 'Self-assessment & revision', duration: `${Math.ceil(hours * 1.5)} hours`, completed: false },
  ];
}

/**
 * Get default resources if Gemini response is invalid
 */
function getDefaultResources() {
  return [
    { title: 'Khan Academy - Core Concepts', type: 'Video Course' as const, url: '#', description: 'Comprehensive video tutorials' },
    { title: 'Practice Problem Set', type: 'Exercises' as const, url: '#', description: 'Hands-on practice exercises' },
    { title: 'Study Group Discord', type: 'Community' as const, url: '#', description: 'Connect with peers' },
    { title: 'Office Hours with TA', type: 'Mentorship' as const, url: '#', description: 'Get personalized help' },
  ];
}

/**
 * Get fallback recovery plan if Gemini fails
 */
function getFallbackRecoveryPlan(student: FirestoreStudent): GeminiRecoveryPlanResponse {
  const weakTopics = student.riskLevel === 'High'
    ? ['Fundamental Concepts', 'Problem Solving', 'Time Management', 'Study Habits']
    : student.riskLevel === 'Medium'
    ? ['Advanced Topics', 'Practical Applications', 'Consistency']
    : ['Optimization', 'Advanced Techniques'];

  return {
    weakTopics,
    dailyStudyHours: student.riskLevel === 'High' ? 4 : student.riskLevel === 'Medium' ? 3 : 2,
    schedule: getDefaultSchedule(student.riskLevel),
    resources: getDefaultResources(),
    strategies: [
      'Break study sessions into 25-minute focused blocks (Pomodoro technique)',
      'Review notes within 24 hours of each lecture',
      'Form a study group with 2-3 classmates',
      'Use active recall instead of passive reading',
      'Attend all office hours for difficult topics',
    ],
  };
}

/**
 * Check if Gemini API is configured
 */
export function isGeminiConfigured(): boolean {
  const apiKey = getGeminiApiKey();
  return !!apiKey && apiKey.trim() !== '';
}

/**
 * Get Gemini API key (for internal use)
 */
export function getGeminiApiKeyValue(): string {
  return getGeminiApiKey();
}

